// File generated by FlutterFire CLI; Android app id aligned to Firebase client
// `com.example.moonguard` (see android/app/build.gradle applicationId).
// ignore_for_file: type=lint, lines_longer_than_80_chars
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart" show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          "DefaultFirebaseOptions have not been configured for linux - "
          "run: dart pub global run flutterfire_cli configure",
        );
      default:
        throw UnsupportedError("DefaultFirebaseOptions are not supported for this platform.");
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB2LwJqPR7yVhTOmaJLBJirH0MFxHMjuoI",
    appId: "1:37745958186:web:43008e177f3d7e93495253",
    messagingSenderId: "37745958186",
    projectId: "agriculture-2f189",
    authDomain: "agriculture-2f189.firebaseapp.com",
    storageBucket: "agriculture-2f189.firebasestorage.app",
    measurementId: "G-LPXN6ZFR9P",
  );

  /// Matches `com.example.moonguard` in `google-services.json` (not `com.example.agriculture`).
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDOJc3hdAN_-Rei2yo1ChXiZqJFr27eGV8",
    appId: "1:37745958186:android:0eafa8bf1928cc2b495253",
    messagingSenderId: "37745958186",
    projectId: "agriculture-2f189",
    storageBucket: "agriculture-2f189.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCbn7KzYATUz75fj1v088V-2yclyzOwd5I",
    appId: "1:37745958186:ios:a96aa59d51122d80495253",
    messagingSenderId: "37745958186",
    projectId: "agriculture-2f189",
    storageBucket: "agriculture-2f189.firebasestorage.app",
    iosBundleId: "com.example.agriculture",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyCbn7KzYATUz75fj1v088V-2yclyzOwd5I",
    appId: "1:37745958186:ios:a96aa59d51122d80495253",
    messagingSenderId: "37745958186",
    projectId: "agriculture-2f189",
    storageBucket: "agriculture-2f189.firebasestorage.app",
    iosBundleId: "com.example.agriculture",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyDYb4pjI_ijtObynByO4r6IxKUYCDBLdqM",
    appId: "1:37745958186:web:ae51d0db3079aebe495253",
    messagingSenderId: "37745958186",
    projectId: "agriculture-2f189",
    authDomain: "agriculture-2f189.firebaseapp.com",
    storageBucket: "agriculture-2f189.firebasestorage.app",
    measurementId: "G-H03WDSLNML",
  );
}
